# Generated by Django 4.2 on 2023-05-06 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(default='c++', max_length=7),
        ),
        migrations.AddField(
            model_name='solution',
            name='problem_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.problem'),
        ),
        migrations.AddField(
            model_name='solution',
            name='program',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='username',
            field=models.ForeignKey(default=None, max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
