# Generated by Django 4.2 on 2023-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_solution_problem_solution_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('C', 'c'), ('C++', 'cpp'), ('Python', 'py'), ('Java', 'java')], max_length=7),
        ),
    ]
