# Generated by Django 4.2 on 2023-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_remove_problem_problem_input_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="program",
            field=models.TextField(),
        ),
    ]
