# Generated by Django 4.2 on 2023-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_solution_program"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solution",
            old_name="program",
            new_name="solution_code",
        ),
        migrations.AlterField(
            model_name="solution",
            name="language",
            field=models.CharField(
                choices=[
                    ("c", "C"),
                    ("cpp", "C++"),
                    ("py", "Python"),
                    ("java", "Java"),
                ],
                max_length=7,
            ),
        ),
    ]
